spring:
  application:
    name: gateway
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}

  main:
    web-application-type: reactive

#redis:
#  host: localhost
#  port: 6379

#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
