spring:
  application:
    name: gateway
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}

  main:
    web-application-type: reactive
#    spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: method_route
          uri: http://localhost:8001
          predicates:
            - Method=GET,POST

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
